name: dt_society_app
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask
  - prophet
  - pandas
  - flask-caching
  - flask-session
  - plotly
  - statsmodels
  - pycountry
  - flask-pymongo
  - scikit-learn
  - flask-cors
  - flask-jwt-extended
