name: dt_society_app
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - flask=2.2.2
  - flask-caching=2.0.1
  - flask-cors=3.0.10
  - flask-jwt-extended=4.4.4
  - flask-pymongo=2.3.0
  - flask-session=0.4.0
  - pandas=1.5.1
  - plotly=5.10.0
  - prophet=1.1.1
  - pycountry=20.7.3
  - python=3.10
  - scikit-learn=1.1.3
  - statsmodels=0.13.2
