name: dt_society
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - pandas
  - tqdm
  - folium==0.12.1.post1
  - ipywidgets
  - pycountry
  - plotly
  - dash
  - black
  - dash-daq
  - statsmodels
  - prophet
  - openpyxl
  - dash-bootstrap-components
